apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: inline-pipeline-test
spec:
  workspaces:
    - name: pipeline-source
  tasks:
    - name: foo
      taskSpec:
        name: fooTask
        steps:
          - name: writefoo
            image: ubuntu
            command: ["bash", "-c"]
            args: ["echo 'foo' > $(workspaces.source.path)/foo"]
        workspaces:
          - name: source
      workspaces:
        - name: source
          workspace: pipeline-source
    - name: bar
      taskSpec:
        name: barTask
        steps:
          - name: writebar
            image: ubuntu
            command: ["bash", "-c"]
            args: ["echo 'bar' > $(workspaces.source.path)/bar"]
        workspaces:
          - name: source
      workspaces:
        - name: source
          workspace: pipeline-source
    - name: afterfoobar
      runAfter: [foo, bar]
      taskSpec:
        name: foobarTask
        steps:
          - name: totals
            image: ubuntu
            command: ["bash", "-c"]
            args: ["du -s $(workspaces.source.path)"]
        workspaces:
          - name: source
      workspaces:
        - name: source
          workspace: pipeline-source