apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: template-test
spec:
  params: []
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipeline-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline-test
        workspaces:
          - name: pipeline-source
            persistentVolumeClaim:
              claimName: pipeline-$(uid)-pvc
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: binding-test
spec:
  params: []
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener-test
spec:
  triggers:
    - binding:
        name: binding-test
      template:
        name: template-test