apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: template-test
spec:
  params: []
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline-test
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: binding-test
spec:
  params: []
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener-test
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: template