apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: footask
spec:
  steps:
    - name: writefoo
      image: alpine
      script: |
        du /workspace/source -s 
        echo 'foo' > $(workspaces.source.path)/foo
  workspaces:
    - name: source
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: bartask
spec:
  steps:
    - name: writefoo
      image: alpine
      script: |
        du /workspace/source -s 
        echo 'bar' > $(workspaces.source.path)/bar
  workspaces:
    - name: source
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: foobartask
spec:
  steps:
    - name: totals
      image: alpine
      script: |
        du /workspace/source -s 
        x=$(du /workspace/source -s | awk '{print $1}' ) && echo $x && ls -al $(workspaces.source.path) && [ "$x" == "12" ]
  workspaces:
    - name: source
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-test
spec:
  workspaces:
    - name: pipeline-source
  tasks:
    - name: foo
      taskRef:
        name: footask
      workspaces:
        - name: source
          workspace: pipeline-source
    - name: bar
      taskRef:
        name: bartask
      workspaces:
        - name: source
          workspace: pipeline-source
    - name: afterfoobar
      runAfter: [foo, bar]
      taskRef:
        name: foobartask
        workspaces:
          - name: source
      workspaces:
        - name: source
          workspace: pipeline-source