apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: footask
spec:
  steps:
    - name: writefoo
      image: alpine
      script: |
        du /workspace/source -s 
        head -c 1000000 </dev/urandom > $(workspaces.source.path)/foo || (sleep 5 && ls -al && exit 1)
  workspaces:
    - name: source
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: bartask
spec:
  steps:
    - name: writebar
      image: alpine
      script: |
        du /workspace/source -s 
        head -c 1000000 </dev/urandom > $(workspaces.source.path)/bar || (sleep 5 && ls -al && exit 1)
  workspaces:
    - name: source
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: foobartask
spec:
  steps:
    - name: totals
      image: alpine
      script: |
        du /workspace/source -s 
        x=$(du /workspace/source -s | awk '{print $1}' ) && echo $x && ls -al $(workspaces.source.path) && [ "$x" == "1964" ] || (sleep 5 && ls -al && exit 1)
  workspaces:
    - name: source
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-test
spec:
  workspaces:
    - name: pipeline-source
  tasks:
    - name: foo
      taskRef:
        name: footask
      workspaces:
        - name: source
          workspace: pipeline-source
    - name: bar
      taskRef:
        name: bartask
      workspaces:
        - name: source
          workspace: pipeline-source
    - name: afterfoobar
      runAfter: [foo, bar]
      taskRef:
        name: foobartask
        workspaces:
          - name: source
      workspaces:
        - name: source
          workspace: pipeline-source