apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: fooTask
spec:
  steps:
    - name: writefoo
      image: ubuntu
      command: ["bash", "-c"]
      args: ["echo 'foo' > $(workspaces.source.path)/foo"]
  workspaces:
    - name: source
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: barTask
spec:
  steps:
    - name: writefoo
      image: ubuntu
      command: ["bash", "-c"]
      args: ["echo 'bar' > $(workspaces.source.path)/bar"]
  workspaces:
    - name: source
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: foobarTask
spec:
  steps:
    - name: totals
      image: ubuntu
      command: ["bash", "-c"]
      args: ["du -s $(workspaces.source.path)"]
  workspaces:
    - name: source
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-test
spec:
  workspaces:
    - name: pipeline-source
  tasks:
    - name: foo
      taskRef:
        name: fooTask
      workspaces:
        - name: source
          workspace: pipeline-source
    - name: bar
      taskRef:
        name: barTask
      workspaces:
        - name: source
          workspace: pipeline-source
    - name: afterfoobar
      runAfter: [foo, bar]
      taskRef:
        name: foobarTask
        workspaces:
          - name: source
      workspaces:
        - name: source
          workspace: pipeline-source